"""Build a mechanical research universe (survivorship-selection fix).

Ranks all active US equities by median dollar volume measured in a window at
the START of the research period (point-in-time information only) and writes
the top-n list to a YAML file consumable by sync_data/run_backtest via
--universe. Residual delisting bias (Alpaca only lists today's active
symbols) is stated in the output file header.

Usage: python3 -m scripts.build_universe --start 2020-07-01 --end 2020-09-30
"""

from __future__ import annotations

import argparse
import asyncio
import logging
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd
import yaml
from src.data.alpaca_data import AlpacaDataClient
from src.data.universe_builder import select_liquid_universe
from src.monitoring.logging_setup import setup_logging
from src.shared.config import load_config, require_env

log = logging.getLogger(__name__)

_HEADER = """\
# Mechanical universe — generated by scripts/build_universe.py, DO NOT hand-edit.
# Method: top {top_n} active US equities by median IEX dollar volume over
# {start}..{end} (information available at period start only — no
# hindsight name-picking). KNOWN residual bias: symbols delisted since then
# are absent from Alpaca's active list, so this fixes SELECTION bias, not
# delisting survivorship. IEX volume used for ranking only (ADR-008).
"""


async def build(args: argparse.Namespace) -> None:
    config = load_config(Path(args.config))
    setup_logging(str(config["monitoring"]["log_level"]))
    ub = config["universe_builder"]
    client = AlpacaDataClient(require_env("ALPACA_API_KEY"), require_env("ALPACA_SECRET_KEY"))
    start = datetime.fromisoformat(args.start).replace(tzinfo=UTC)
    end = datetime.fromisoformat(args.end).replace(tzinfo=UTC)

    symbols = await client.fetch_active_symbols(list(config["screener"]["exchanges"]))
    batch_size = int(ub["batch_size"])
    rows = []
    for i in range(0, len(symbols), batch_size):
        batch = symbols[i : i + batch_size]
        bars_by_symbol = await client.fetch_bars_multi(batch, start, end, skip_invalid=True)
        for symbol, bars in bars_by_symbol.items():
            rows.extend(
                {"symbol": symbol, "timestamp": b.timestamp, "close": b.close, "volume": b.volume}
                for b in bars
            )
        log.info(
            "universe_scan_progress",
            extra={"scanned": min(i + batch_size, len(symbols)), "total": len(symbols)},
        )

    universe = select_liquid_universe(
        pd.DataFrame(rows),
        min_price=float(config["screener"]["min_price"]),
        min_days=int(ub["min_days"]),
        top_n=int(ub["top_n"]),
    )
    out = Path(args.out)
    header = _HEADER.format(top_n=ub["top_n"], start=args.start, end=args.end)
    body = yaml.safe_dump(
        {"generated_at": datetime.now(tz=UTC).isoformat(), "universe": universe},
        sort_keys=False,
    )
    out.write_text(header + body, encoding="utf-8")
    log.info("universe_written", extra={"path": str(out), "size": len(universe)})


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--start", required=True)
    parser.add_argument("--end", required=True)
    parser.add_argument("--config", default="config/base.yaml")
    parser.add_argument("--out", default="config/universe_mech.yaml")
    asyncio.run(build(parser.parse_args()))


if __name__ == "__main__":
    main()
